FROM golang:1.25.5-alpine

WORKDIR /app

# air (ホットリロード) をインストール
RUN go install github.com/air-verse/air@latest

# 依存関係をインストール
COPY go.mod go.sum ./
RUN go mod download

# golang migrate(postgres)
RUN go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest
RUN go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
RUN go install github.com/go-delve/delve/cmd/dlv@latest

# ソースコードをコピー
COPY . .

EXPOSE 8080

CMD ["air"]
