// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createAuthUser = `-- name: CreateAuthUser :one
INSERT INTO "user" (
  id,
  name,
  email,
  "emailVerified",
  image,
  points,
  "createdAt",
  "updatedAt"
) VALUES (
  $1, $2, $3, $4, $5, $6, now(), now()
)
RETURNING id, name, email, "emailVerified", image, points, "createdAt", "updatedAt"
`

type CreateAuthUserParams struct {
	ID            string         `json:"id"`
	Name          string         `json:"name"`
	Email         string         `json:"email"`
	EmailVerified bool           `json:"emailVerified"`
	Image         sql.NullString `json:"image"`
	Points        int32          `json:"points"`
}

func (q *Queries) CreateAuthUser(ctx context.Context, arg CreateAuthUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createAuthUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.EmailVerified,
		arg.Image,
		arg.Points,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.Points,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCredentialAccount = `-- name: CreateCredentialAccount :one
INSERT INTO "account" (
  id,
  "accountId",
  "providerId",
  "userId",
  password,
  "createdAt",
  "updatedAt"
) VALUES (
  $1, $2, 'credential', $3, $4, now(), now()
)
RETURNING id, "accountId", "providerId", "userId", password, "createdAt", "updatedAt"
`

type CreateCredentialAccountParams struct {
	ID        string         `json:"id"`
	AccountId string         `json:"accountId"`
	UserId    string         `json:"userId"`
	Password  sql.NullString `json:"password"`
}

type CreateCredentialAccountRow struct {
	ID         string         `json:"id"`
	AccountId  string         `json:"accountId"`
	ProviderId string         `json:"providerId"`
	UserId     string         `json:"userId"`
	Password   sql.NullString `json:"password"`
	CreatedAt  time.Time      `json:"createdAt"`
	UpdatedAt  time.Time      `json:"updatedAt"`
}

func (q *Queries) CreateCredentialAccount(ctx context.Context, arg CreateCredentialAccountParams) (CreateCredentialAccountRow, error) {
	row := q.db.QueryRowContext(ctx, createCredentialAccount,
		arg.ID,
		arg.AccountId,
		arg.UserId,
		arg.Password,
	)
	var i CreateCredentialAccountRow
	err := row.Scan(
		&i.ID,
		&i.AccountId,
		&i.ProviderId,
		&i.UserId,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
