// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: category_tags.sql

package db

import (
	"context"
)

const createCategoryTag = `-- name: CreateCategoryTag :one
INSERT INTO category_tags (
  name
) VALUES (
  $1
)
RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreateCategoryTag(ctx context.Context, name string) (CategoryTag, error) {
	row := q.db.QueryRowContext(ctx, createCategoryTag, name)
	var i CategoryTag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
