// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comments.sql

package db

import (
	"context"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments (
  program_id,
  content
) VALUES (
  $1, $2
)
RETURNING id, program_id, content, created_at, updated_at
`

type CreateCommentParams struct {
	ProgramID int64  `json:"program_id"`
	Content   string `json:"content"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRowContext(ctx, createComment, arg.ProgramID, arg.Content)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.ProgramID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
