// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: likes.sql

package db

import (
	"context"
)

const countLikesByProgramID = `-- name: CountLikesByProgramID :one
SELECT COUNT(*)::bigint AS like_count
FROM likes
WHERE program_id = $1
`

func (q *Queries) CountLikesByProgramID(ctx context.Context, programID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLikesByProgramID, programID)
	var like_count int64
	err := row.Scan(&like_count)
	return like_count, err
}

const createLike = `-- name: CreateLike :exec
INSERT INTO likes (user_id, program_id)
VALUES ($1, $2)
ON CONFLICT (user_id, program_id) DO NOTHING
`

type CreateLikeParams struct {
	UserID    string `json:"user_id"`
	ProgramID int64  `json:"program_id"`
}

func (q *Queries) CreateLike(ctx context.Context, arg CreateLikeParams) error {
	_, err := q.db.ExecContext(ctx, createLike, arg.UserID, arg.ProgramID)
	return err
}

const deleteLike = `-- name: DeleteLike :exec
DELETE FROM likes
WHERE user_id = $1 AND program_id = $2
`

type DeleteLikeParams struct {
	UserID    string `json:"user_id"`
	ProgramID int64  `json:"program_id"`
}

func (q *Queries) DeleteLike(ctx context.Context, arg DeleteLikeParams) error {
	_, err := q.db.ExecContext(ctx, deleteLike, arg.UserID, arg.ProgramID)
	return err
}

const hasUserLikedProgram = `-- name: HasUserLikedProgram :one
SELECT EXISTS(
  SELECT 1
  FROM likes
  WHERE user_id = $1 AND program_id = $2
) AS liked
`

type HasUserLikedProgramParams struct {
	UserID    string `json:"user_id"`
	ProgramID int64  `json:"program_id"`
}

func (q *Queries) HasUserLikedProgram(ctx context.Context, arg HasUserLikedProgramParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasUserLikedProgram, arg.UserID, arg.ProgramID)
	var liked bool
	err := row.Scan(&liked)
	return liked, err
}
