// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: maintenance.sql

package db

import (
	"context"
)

const clearAllData = `-- name: ClearAllData :exec
TRUNCATE TABLE
  likes,
  watch_histories,
  "verification",
  "account",
  "session",
  "user",
  comments,
  program_category_tags,
  program_performers,
  programs,
  category_tags,
  performers
RESTART IDENTITY CASCADE
`

func (q *Queries) ClearAllData(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearAllData)
	return err
}
