// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Account struct {
	ID                    string         `json:"id"`
	AccountId             string         `json:"accountId"`
	ProviderId            string         `json:"providerId"`
	UserId                string         `json:"userId"`
	AccessToken           sql.NullString `json:"accessToken"`
	RefreshToken          sql.NullString `json:"refreshToken"`
	IdToken               sql.NullString `json:"idToken"`
	AccessTokenExpiresAt  sql.NullTime   `json:"accessTokenExpiresAt"`
	RefreshTokenExpiresAt sql.NullTime   `json:"refreshTokenExpiresAt"`
	Scope                 sql.NullString `json:"scope"`
	Password              sql.NullString `json:"password"`
	CreatedAt             time.Time      `json:"createdAt"`
	UpdatedAt             time.Time      `json:"updatedAt"`
}

type CategoryTag struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Comment struct {
	ID        int64          `json:"id"`
	ProgramID int64          `json:"program_id"`
	UserID    sql.NullString `json:"user_id"`
	Content   string         `json:"content"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type Like struct {
	ID        int64     `json:"id"`
	UserID    string    `json:"user_id"`
	ProgramID int64     `json:"program_id"`
	CreatedAt time.Time `json:"created_at"`
}

type PaypayTopup struct {
	ID                int64          `json:"id"`
	UserID            string         `json:"user_id"`
	MerchantPaymentID string         `json:"merchant_payment_id"`
	AmountYen         int32          `json:"amount_yen"`
	Status            string         `json:"status"`
	PaypayCodeID      sql.NullString `json:"paypay_code_id"`
	PaypayPaymentID   sql.NullString `json:"paypay_payment_id"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	CreditedAt        sql.NullTime   `json:"credited_at"`
}

type Performer struct {
	ID            int64          `json:"id"`
	FirstName     string         `json:"first_name"`
	LastName      string         `json:"last_name"`
	FirstNameKana string         `json:"first_name_kana"`
	LastNameKana  string         `json:"last_name_kana"`
	ImagePath     sql.NullString `json:"image_path"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

type PermittedProgramUser struct {
	ID        int64     `json:"id"`
	UserID    string    `json:"user_id"`
	ProgramID int64     `json:"program_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Program struct {
	ID               int64          `json:"id"`
	Title            string         `json:"title"`
	VideoPath        string         `json:"video_path"`
	ThumbnailPath    sql.NullString `json:"thumbnail_path"`
	Description      sql.NullString `json:"description"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	ViewCount        int32          `json:"view_count"`
	IsLimitedRelease bool           `json:"is_limited_release"`
	Price            int32          `json:"price"`
	IsPublic         bool           `json:"is_public"`
}

type ProgramCategoryTag struct {
	ProgramID int64 `json:"program_id"`
	TagID     int64 `json:"tag_id"`
}

type ProgramPerformer struct {
	ProgramID   int64 `json:"program_id"`
	PerformerID int64 `json:"performer_id"`
}

type Request struct {
	ID        int64          `json:"id"`
	UserID    sql.NullString `json:"user_id"`
	Content   string         `json:"content"`
	Name      string         `json:"name"`
	Contact   string         `json:"contact"`
	Note      string         `json:"note"`
	CreatedAt time.Time      `json:"created_at"`
}

type Session struct {
	ID        string         `json:"id"`
	ExpiresAt time.Time      `json:"expiresAt"`
	Token     string         `json:"token"`
	CreatedAt time.Time      `json:"createdAt"`
	UpdatedAt time.Time      `json:"updatedAt"`
	IpAddress sql.NullString `json:"ipAddress"`
	UserAgent sql.NullString `json:"userAgent"`
	UserId    string         `json:"userId"`
}

type User struct {
	ID            string         `json:"id"`
	Name          string         `json:"name"`
	Email         string         `json:"email"`
	EmailVerified bool           `json:"emailVerified"`
	Image         sql.NullString `json:"image"`
	Points        int32          `json:"points"`
	CreatedAt     time.Time      `json:"createdAt"`
	UpdatedAt     time.Time      `json:"updatedAt"`
}

type Verification struct {
	ID         string    `json:"id"`
	Identifier string    `json:"identifier"`
	Value      string    `json:"value"`
	ExpiresAt  time.Time `json:"expiresAt"`
	CreatedAt  time.Time `json:"createdAt"`
	UpdatedAt  time.Time `json:"updatedAt"`
}

type WatchHistory struct {
	ID              int64     `json:"id"`
	UserID          string    `json:"user_id"`
	ProgramID       int64     `json:"program_id"`
	PositionSeconds int32     `json:"position_seconds"`
	IsCompleted     bool      `json:"is_completed"`
	LastWatchedAt   time.Time `json:"last_watched_at"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}
