// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type CategoryTag struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Comment struct {
	ID        int64     `json:"id"`
	ProgramID int64     `json:"program_id"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Performer struct {
	ID            int64          `json:"id"`
	FirstName     string         `json:"first_name"`
	LastName      string         `json:"last_name"`
	FirstNameKana string         `json:"first_name_kana"`
	LastNameKana  string         `json:"last_name_kana"`
	ImagePath     sql.NullString `json:"image_path"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

type Program struct {
	ID            int64          `json:"id"`
	Title         string         `json:"title"`
	VideoPath     string         `json:"video_path"`
	ThumbnailPath sql.NullString `json:"thumbnail_path"`
	Description   sql.NullString `json:"description"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

type ProgramCategoryTag struct {
	ProgramID int64 `json:"program_id"`
	TagID     int64 `json:"tag_id"`
}

type ProgramPerformer struct {
	ProgramID   int64 `json:"program_id"`
	PerformerID int64 `json:"performer_id"`
}
