// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Account struct {
	ID                    string         `json:"id"`
	AccountId             string         `json:"accountId"`
	ProviderId            string         `json:"providerId"`
	UserId                string         `json:"userId"`
	AccessToken           sql.NullString `json:"accessToken"`
	RefreshToken          sql.NullString `json:"refreshToken"`
	IdToken               sql.NullString `json:"idToken"`
	AccessTokenExpiresAt  sql.NullTime   `json:"accessTokenExpiresAt"`
	RefreshTokenExpiresAt sql.NullTime   `json:"refreshTokenExpiresAt"`
	Scope                 sql.NullString `json:"scope"`
	Password              sql.NullString `json:"password"`
	CreatedAt             time.Time      `json:"createdAt"`
	UpdatedAt             time.Time      `json:"updatedAt"`
}

type CategoryTag struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Comment struct {
	ID        int64     `json:"id"`
	ProgramID int64     `json:"program_id"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Like struct {
	ID        int64     `json:"id"`
	UserID    string    `json:"user_id"`
	ProgramID int64     `json:"program_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Performer struct {
	ID            int64          `json:"id"`
	FirstName     string         `json:"first_name"`
	LastName      string         `json:"last_name"`
	FirstNameKana string         `json:"first_name_kana"`
	LastNameKana  string         `json:"last_name_kana"`
	ImagePath     sql.NullString `json:"image_path"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

type Program struct {
	ID            int64          `json:"id"`
	Title         string         `json:"title"`
	VideoPath     string         `json:"video_path"`
	ThumbnailPath sql.NullString `json:"thumbnail_path"`
	Description   sql.NullString `json:"description"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

type ProgramCategoryTag struct {
	ProgramID int64 `json:"program_id"`
	TagID     int64 `json:"tag_id"`
}

type ProgramPerformer struct {
	ProgramID   int64 `json:"program_id"`
	PerformerID int64 `json:"performer_id"`
}

type Session struct {
	ID        string         `json:"id"`
	ExpiresAt time.Time      `json:"expiresAt"`
	Token     string         `json:"token"`
	CreatedAt time.Time      `json:"createdAt"`
	UpdatedAt time.Time      `json:"updatedAt"`
	IpAddress sql.NullString `json:"ipAddress"`
	UserAgent sql.NullString `json:"userAgent"`
	UserId    string         `json:"userId"`
}

type User struct {
	ID            string         `json:"id"`
	Name          string         `json:"name"`
	Email         string         `json:"email"`
	EmailVerified bool           `json:"emailVerified"`
	Image         sql.NullString `json:"image"`
	CreatedAt     time.Time      `json:"createdAt"`
	UpdatedAt     time.Time      `json:"updatedAt"`
}

type Verification struct {
	ID         string    `json:"id"`
	Identifier string    `json:"identifier"`
	Value      string    `json:"value"`
	ExpiresAt  time.Time `json:"expiresAt"`
	CreatedAt  time.Time `json:"createdAt"`
	UpdatedAt  time.Time `json:"updatedAt"`
}

type WatchHistory struct {
	ID              int64     `json:"id"`
	UserID          string    `json:"user_id"`
	ProgramID       int64     `json:"program_id"`
	PositionSeconds int32     `json:"position_seconds"`
	IsCompleted     bool      `json:"is_completed"`
	LastWatchedAt   time.Time `json:"last_watched_at"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}
