// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mypage.sql

package db

import (
	"context"
	"database/sql"
)

const listLikedProgramsByUser = `-- name: ListLikedProgramsByUser :many
SELECT
  p.id AS program_id,
  p.title,
  p.thumbnail_path,
  p.view_count,
  p.is_limited_release,
  p.price,
  COALESCE((SELECT COUNT(*) FROM likes l WHERE l.program_id = p.id), 0)::bigint AS like_count,
  COALESCE(
    jsonb_agg(DISTINCT jsonb_build_object(
      'id', ct.id,
      'name', ct.name
    )) FILTER (WHERE ct.id IS NOT NULL),
    '[]'::jsonb
  ) AS category_tags
FROM likes lk
JOIN programs p ON p.id = lk.program_id
LEFT JOIN program_category_tags pct ON p.id = pct.program_id
LEFT JOIN category_tags ct ON pct.tag_id = ct.id
WHERE lk.user_id = $1 AND p.is_public = true
GROUP BY
  p.id,
  p.title,
  p.thumbnail_path,
  p.view_count,
  p.is_limited_release,
  p.price,
  lk.created_at
ORDER BY lk.created_at DESC
LIMIT COALESCE($3::int, 50)
OFFSET COALESCE($2::int, 0)
`

type ListLikedProgramsByUserParams struct {
	UserID string        `json:"user_id"`
	Offset sql.NullInt32 `json:"offset"`
	Limit  sql.NullInt32 `json:"limit"`
}

type ListLikedProgramsByUserRow struct {
	ProgramID        int64          `json:"program_id"`
	Title            string         `json:"title"`
	ThumbnailPath    sql.NullString `json:"thumbnail_path"`
	ViewCount        int32          `json:"view_count"`
	IsLimitedRelease bool           `json:"is_limited_release"`
	Price            int32          `json:"price"`
	LikeCount        int64          `json:"like_count"`
	CategoryTags     interface{}    `json:"category_tags"`
}

// 視聴回数はprogramsテーブルのview_countを参照
func (q *Queries) ListLikedProgramsByUser(ctx context.Context, arg ListLikedProgramsByUserParams) ([]ListLikedProgramsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listLikedProgramsByUser, arg.UserID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLikedProgramsByUserRow
	for rows.Next() {
		var i ListLikedProgramsByUserRow
		if err := rows.Scan(
			&i.ProgramID,
			&i.Title,
			&i.ThumbnailPath,
			&i.ViewCount,
			&i.IsLimitedRelease,
			&i.Price,
			&i.LikeCount,
			&i.CategoryTags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWatchingProgramsByUser = `-- name: ListWatchingProgramsByUser :many
SELECT
  p.id AS program_id,
  p.title,
  p.thumbnail_path,
  p.view_count,
  p.is_limited_release,
  p.price,
  COALESCE((SELECT COUNT(*) FROM likes l WHERE l.program_id = p.id), 0)::bigint AS like_count,
  COALESCE(
    jsonb_agg(DISTINCT jsonb_build_object(
      'id', ct.id,
      'name', ct.name
    )) FILTER (WHERE ct.id IS NOT NULL),
    '[]'::jsonb
  ) AS category_tags
FROM watch_histories wh
JOIN programs p ON p.id = wh.program_id
LEFT JOIN program_category_tags pct ON p.id = pct.program_id
LEFT JOIN category_tags ct ON pct.tag_id = ct.id
WHERE wh.user_id = $1 AND wh.is_completed = FALSE AND p.is_public = true
GROUP BY
  p.id,
  p.title,
  p.thumbnail_path,
  p.view_count,
  p.is_limited_release,
  p.price,
  wh.last_watched_at
ORDER BY wh.last_watched_at DESC
LIMIT COALESCE($3::int, 50)
OFFSET COALESCE($2::int, 0)
`

type ListWatchingProgramsByUserParams struct {
	UserID string        `json:"user_id"`
	Offset sql.NullInt32 `json:"offset"`
	Limit  sql.NullInt32 `json:"limit"`
}

type ListWatchingProgramsByUserRow struct {
	ProgramID        int64          `json:"program_id"`
	Title            string         `json:"title"`
	ThumbnailPath    sql.NullString `json:"thumbnail_path"`
	ViewCount        int32          `json:"view_count"`
	IsLimitedRelease bool           `json:"is_limited_release"`
	Price            int32          `json:"price"`
	LikeCount        int64          `json:"like_count"`
	CategoryTags     interface{}    `json:"category_tags"`
}

// 視聴回数はprogramsテーブルのview_countを参照
func (q *Queries) ListWatchingProgramsByUser(ctx context.Context, arg ListWatchingProgramsByUserParams) ([]ListWatchingProgramsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listWatchingProgramsByUser, arg.UserID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWatchingProgramsByUserRow
	for rows.Next() {
		var i ListWatchingProgramsByUserRow
		if err := rows.Scan(
			&i.ProgramID,
			&i.Title,
			&i.ThumbnailPath,
			&i.ViewCount,
			&i.IsLimitedRelease,
			&i.Price,
			&i.LikeCount,
			&i.CategoryTags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
