// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: paypay_topups.sql

package db

import (
	"context"
	"database/sql"
)

const createPayPayTopup = `-- name: CreatePayPayTopup :one

INSERT INTO paypay_topups (
  user_id,
  merchant_payment_id,
  amount_yen,
  status
) VALUES (
  $1,
  $2,
  $3,
  'CREATED'
)
RETURNING id, user_id, merchant_payment_id, amount_yen, status, paypay_code_id, paypay_payment_id, created_at, updated_at, credited_at
`

type CreatePayPayTopupParams struct {
	UserID            string `json:"user_id"`
	MerchantPaymentID string `json:"merchant_payment_id"`
	AmountYen         int32  `json:"amount_yen"`
}

// PayPay topups (user purchases points via PayPay)
func (q *Queries) CreatePayPayTopup(ctx context.Context, arg CreatePayPayTopupParams) (PaypayTopup, error) {
	row := q.db.QueryRowContext(ctx, createPayPayTopup, arg.UserID, arg.MerchantPaymentID, arg.AmountYen)
	var i PaypayTopup
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MerchantPaymentID,
		&i.AmountYen,
		&i.Status,
		&i.PaypayCodeID,
		&i.PaypayPaymentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreditedAt,
	)
	return i, err
}

const getPayPayTopupForUpdate = `-- name: GetPayPayTopupForUpdate :one
SELECT id, user_id, merchant_payment_id, amount_yen, status, paypay_code_id, paypay_payment_id, created_at, updated_at, credited_at
FROM paypay_topups
WHERE user_id = $1
  AND merchant_payment_id = $2
FOR UPDATE
`

type GetPayPayTopupForUpdateParams struct {
	UserID            string `json:"user_id"`
	MerchantPaymentID string `json:"merchant_payment_id"`
}

func (q *Queries) GetPayPayTopupForUpdate(ctx context.Context, arg GetPayPayTopupForUpdateParams) (PaypayTopup, error) {
	row := q.db.QueryRowContext(ctx, getPayPayTopupForUpdate, arg.UserID, arg.MerchantPaymentID)
	var i PaypayTopup
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MerchantPaymentID,
		&i.AmountYen,
		&i.Status,
		&i.PaypayCodeID,
		&i.PaypayPaymentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreditedAt,
	)
	return i, err
}

const markPayPayTopupCredited = `-- name: MarkPayPayTopupCredited :execrows
UPDATE paypay_topups
SET credited_at = now(),
    status = 'COMPLETED',
    paypay_payment_id = $3,
    updated_at = now()
WHERE user_id = $1
  AND merchant_payment_id = $2
  AND credited_at IS NULL
`

type MarkPayPayTopupCreditedParams struct {
	UserID            string         `json:"user_id"`
	MerchantPaymentID string         `json:"merchant_payment_id"`
	PaypayPaymentID   sql.NullString `json:"paypay_payment_id"`
}

func (q *Queries) MarkPayPayTopupCredited(ctx context.Context, arg MarkPayPayTopupCreditedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markPayPayTopupCredited, arg.UserID, arg.MerchantPaymentID, arg.PaypayPaymentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setPayPayTopupCode = `-- name: SetPayPayTopupCode :exec
UPDATE paypay_topups
SET paypay_code_id = $3,
    updated_at = now()
WHERE user_id = $1
  AND merchant_payment_id = $2
`

type SetPayPayTopupCodeParams struct {
	UserID            string         `json:"user_id"`
	MerchantPaymentID string         `json:"merchant_payment_id"`
	PaypayCodeID      sql.NullString `json:"paypay_code_id"`
}

func (q *Queries) SetPayPayTopupCode(ctx context.Context, arg SetPayPayTopupCodeParams) error {
	_, err := q.db.ExecContext(ctx, setPayPayTopupCode, arg.UserID, arg.MerchantPaymentID, arg.PaypayCodeID)
	return err
}

const updatePayPayTopupStatus = `-- name: UpdatePayPayTopupStatus :exec
UPDATE paypay_topups
SET status = $3,
    paypay_payment_id = COALESCE($4, paypay_payment_id),
    updated_at = now()
WHERE user_id = $1
  AND merchant_payment_id = $2
`

type UpdatePayPayTopupStatusParams struct {
	UserID            string         `json:"user_id"`
	MerchantPaymentID string         `json:"merchant_payment_id"`
	Status            string         `json:"status"`
	PaypayPaymentID   sql.NullString `json:"paypay_payment_id"`
}

func (q *Queries) UpdatePayPayTopupStatus(ctx context.Context, arg UpdatePayPayTopupStatusParams) error {
	_, err := q.db.ExecContext(ctx, updatePayPayTopupStatus,
		arg.UserID,
		arg.MerchantPaymentID,
		arg.Status,
		arg.PaypayPaymentID,
	)
	return err
}
