// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: performers.sql

package db

import (
	"context"
	"database/sql"
)

const createPerformer = `-- name: CreatePerformer :one
INSERT INTO performers (
  first_name,
  last_name,
  first_name_kana,
  last_name_kana,
  image_path
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, first_name, last_name, first_name_kana, last_name_kana, image_path, created_at, updated_at
`

type CreatePerformerParams struct {
	FirstName     string         `json:"first_name"`
	LastName      string         `json:"last_name"`
	FirstNameKana string         `json:"first_name_kana"`
	LastNameKana  string         `json:"last_name_kana"`
	ImagePath     sql.NullString `json:"image_path"`
}

func (q *Queries) CreatePerformer(ctx context.Context, arg CreatePerformerParams) (Performer, error) {
	row := q.db.QueryRowContext(ctx, createPerformer,
		arg.FirstName,
		arg.LastName,
		arg.FirstNameKana,
		arg.LastNameKana,
		arg.ImagePath,
	)
	var i Performer
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.FirstNameKana,
		&i.LastNameKana,
		&i.ImagePath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
