// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: permitted_program_users.sql

package db

import (
	"context"
)

const addPermittedProgramUser = `-- name: AddPermittedProgramUser :exec
INSERT INTO permitted_program_users (user_id, program_id)
VALUES ($1, $2)
ON CONFLICT (user_id, program_id) DO NOTHING
`

type AddPermittedProgramUserParams struct {
	UserID    string `json:"user_id"`
	ProgramID int64  `json:"program_id"`
}

func (q *Queries) AddPermittedProgramUser(ctx context.Context, arg AddPermittedProgramUserParams) error {
	_, err := q.db.ExecContext(ctx, addPermittedProgramUser, arg.UserID, arg.ProgramID)
	return err
}

const isUserPermittedForProgram = `-- name: IsUserPermittedForProgram :one
SELECT EXISTS (
  SELECT 1 FROM permitted_program_users
  WHERE user_id = $1 AND program_id = $2
) AS is_permitted
`

type IsUserPermittedForProgramParams struct {
	UserID    string `json:"user_id"`
	ProgramID int64  `json:"program_id"`
}

func (q *Queries) IsUserPermittedForProgram(ctx context.Context, arg IsUserPermittedForProgramParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isUserPermittedForProgram, arg.UserID, arg.ProgramID)
	var is_permitted bool
	err := row.Scan(&is_permitted)
	return is_permitted, err
}

const removePermittedProgramUser = `-- name: RemovePermittedProgramUser :exec
DELETE FROM permitted_program_users
WHERE user_id = $1 AND program_id = $2
`

type RemovePermittedProgramUserParams struct {
	UserID    string `json:"user_id"`
	ProgramID int64  `json:"program_id"`
}

func (q *Queries) RemovePermittedProgramUser(ctx context.Context, arg RemovePermittedProgramUserParams) error {
	_, err := q.db.ExecContext(ctx, removePermittedProgramUser, arg.UserID, arg.ProgramID)
	return err
}
