// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: programs.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/lib/pq"
)

const createProgram = `-- name: CreateProgram :one
INSERT INTO programs (
  title,
  video_path,
  thumbnail_path,
  description
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, title, video_path, thumbnail_path, description, created_at, updated_at
`

type CreateProgramParams struct {
	Title         string         `json:"title"`
	VideoPath     string         `json:"video_path"`
	ThumbnailPath sql.NullString `json:"thumbnail_path"`
	Description   sql.NullString `json:"description"`
}

func (q *Queries) CreateProgram(ctx context.Context, arg CreateProgramParams) (Program, error) {
	row := q.db.QueryRowContext(ctx, createProgram,
		arg.Title,
		arg.VideoPath,
		arg.ThumbnailPath,
		arg.Description,
	)
	var i Program
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.VideoPath,
		&i.ThumbnailPath,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProgramByID = `-- name: GetProgramByID :one
SELECT
  p.id AS program_id,
  p.title,
  p.video_path,
  p.thumbnail_path,
  p.description,
  COALESCE(wc.view_count, 0)::bigint AS view_count,
  p.created_at AS program_created_at,
  p.updated_at AS program_updated_at,
  COALESCE(
    jsonb_agg(DISTINCT jsonb_build_object(
      'id', ct.id,
      'name', ct.name
    )) FILTER (WHERE ct.id IS NOT NULL),
    '[]'::jsonb
  ) AS category_tags,
  COALESCE(
    jsonb_agg(DISTINCT jsonb_build_object(
      'id', pe.id,
      'first_name', pe.first_name,
      'last_name', pe.last_name,
      'first_name_kana', pe.first_name_kana,
      'last_name_kana', pe.last_name_kana,
      'image_path', pe.image_path
    )) FILTER (WHERE pe.id IS NOT NULL),
    '[]'::jsonb
  ) AS performers
FROM programs p
LEFT JOIN (
  SELECT program_id, COUNT(*)::bigint AS view_count
  FROM watch_histories
  GROUP BY program_id
) wc ON wc.program_id = p.id
LEFT JOIN program_category_tags pct ON p.id = pct.program_id
LEFT JOIN category_tags ct ON pct.tag_id = ct.id
LEFT JOIN program_performers pp ON p.id = pp.program_id
LEFT JOIN performers pe ON pp.performer_id = pe.id
WHERE p.id = $1
GROUP BY
  p.id,
  p.title,
  p.video_path,
  p.thumbnail_path,
  p.description,
  wc.view_count,
  p.created_at,
  p.updated_at
`

type GetProgramByIDRow struct {
	ProgramID        int64          `json:"program_id"`
	Title            string         `json:"title"`
	VideoPath        string         `json:"video_path"`
	ThumbnailPath    sql.NullString `json:"thumbnail_path"`
	Description      sql.NullString `json:"description"`
	ViewCount        int64          `json:"view_count"`
	ProgramCreatedAt time.Time      `json:"program_created_at"`
	ProgramUpdatedAt time.Time      `json:"program_updated_at"`
	CategoryTags     interface{}    `json:"category_tags"`
	Performers       interface{}    `json:"performers"`
}

func (q *Queries) GetProgramByID(ctx context.Context, id int64) (GetProgramByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getProgramByID, id)
	var i GetProgramByIDRow
	err := row.Scan(
		&i.ProgramID,
		&i.Title,
		&i.VideoPath,
		&i.ThumbnailPath,
		&i.Description,
		&i.ViewCount,
		&i.ProgramCreatedAt,
		&i.ProgramUpdatedAt,
		&i.CategoryTags,
		&i.Performers,
	)
	return i, err
}

const getPrograms = `-- name: GetPrograms :many
SELECT
  p.id AS program_id,
  p.title,
  p.thumbnail_path,
  COALESCE(wc.view_count, 0)::bigint AS view_count,
  COALESCE(
    jsonb_agg(DISTINCT jsonb_build_object(
      'id', ct.id,
      'name', ct.name
    )) FILTER (WHERE ct.id IS NOT NULL),
    '[]'::jsonb
  ) AS category_tags
FROM programs p
LEFT JOIN (
  SELECT program_id, COUNT(*)::bigint AS view_count
  FROM watch_histories
  GROUP BY program_id
) wc ON wc.program_id = p.id
LEFT JOIN program_category_tags pct ON p.id = pct.program_id
LEFT JOIN category_tags ct ON pct.tag_id = ct.id
WHERE
  ($1::text IS NULL OR p.title ILIKE '%' || $1::text || '%')
  AND (
    $2::bigint[] IS NULL
    OR p.id IN (
      SELECT pct2.program_id
      FROM program_category_tags pct2
      WHERE pct2.tag_id = ANY($2::bigint[])
      GROUP BY pct2.program_id
      HAVING COUNT(DISTINCT pct2.tag_id) = array_length($2::bigint[], 1)
    )
  )
GROUP BY
  p.id,
  p.title,
  p.thumbnail_path,
  wc.view_count
`

type GetProgramsParams struct {
	Title  sql.NullString `json:"title"`
	TagIds []int64        `json:"tag_ids"`
}

type GetProgramsRow struct {
	ProgramID     int64          `json:"program_id"`
	Title         string         `json:"title"`
	ThumbnailPath sql.NullString `json:"thumbnail_path"`
	ViewCount     int64          `json:"view_count"`
	CategoryTags  interface{}    `json:"category_tags"`
}

func (q *Queries) GetPrograms(ctx context.Context, arg GetProgramsParams) ([]GetProgramsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPrograms, arg.Title, pq.Array(arg.TagIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProgramsRow
	for rows.Next() {
		var i GetProgramsRow
		if err := rows.Scan(
			&i.ProgramID,
			&i.Title,
			&i.ThumbnailPath,
			&i.ViewCount,
			&i.CategoryTags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopPrograms = `-- name: GetTopPrograms :many
SELECT
  p.id AS program_id,
  p.title,
  p.thumbnail_path,
  COALESCE(wc.view_count, 0)::bigint AS view_count
FROM programs p
LEFT JOIN (
  SELECT program_id, COUNT(*)::bigint AS view_count
  FROM watch_histories
  GROUP BY program_id
) wc ON wc.program_id = p.id
ORDER BY p.created_at DESC
LIMIT 5
`

type GetTopProgramsRow struct {
	ProgramID     int64          `json:"program_id"`
	Title         string         `json:"title"`
	ThumbnailPath sql.NullString `json:"thumbnail_path"`
	ViewCount     int64          `json:"view_count"`
}

func (q *Queries) GetTopPrograms(ctx context.Context) ([]GetTopProgramsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTopPrograms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopProgramsRow
	for rows.Next() {
		var i GetTopProgramsRow
		if err := rows.Scan(
			&i.ProgramID,
			&i.Title,
			&i.ThumbnailPath,
			&i.ViewCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
