// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: program_category_tags.sql

package db

import (
	"context"
)

const createProgramCategoryTag = `-- name: CreateProgramCategoryTag :exec
INSERT INTO program_category_tags (
  program_id,
  tag_id
) VALUES (
  $1, $2
)
`

type CreateProgramCategoryTagParams struct {
	ProgramID int64 `json:"program_id"`
	TagID     int64 `json:"tag_id"`
}

func (q *Queries) CreateProgramCategoryTag(ctx context.Context, arg CreateProgramCategoryTagParams) error {
	_, err := q.db.ExecContext(ctx, createProgramCategoryTag, arg.ProgramID, arg.TagID)
	return err
}
