// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: program_performers.sql

package db

import (
	"context"
)

const createProgramPerformer = `-- name: CreateProgramPerformer :exec
INSERT INTO program_performers (
  program_id,
  performer_id
) VALUES (
  $1, $2
)
`

type CreateProgramPerformerParams struct {
	ProgramID   int64 `json:"program_id"`
	PerformerID int64 `json:"performer_id"`
}

func (q *Queries) CreateProgramPerformer(ctx context.Context, arg CreateProgramPerformerParams) error {
	_, err := q.db.ExecContext(ctx, createProgramPerformer, arg.ProgramID, arg.PerformerID)
	return err
}
