// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: requests.sql

package db

import (
	"context"
	"database/sql"
)

const createRequest = `-- name: CreateRequest :one
INSERT INTO requests (user_id, content, name, contact, note)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, content, name, contact, note, created_at
`

type CreateRequestParams struct {
	UserID  sql.NullString `json:"user_id"`
	Content string         `json:"content"`
	Name    string         `json:"name"`
	Contact string         `json:"contact"`
	Note    string         `json:"note"`
}

func (q *Queries) CreateRequest(ctx context.Context, arg CreateRequestParams) (Request, error) {
	row := q.db.QueryRowContext(ctx, createRequest,
		arg.UserID,
		arg.Content,
		arg.Name,
		arg.Contact,
		arg.Note,
	)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Content,
		&i.Name,
		&i.Contact,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}
