// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
)

const addPointsToUser = `-- name: AddPointsToUser :one
UPDATE "user"
SET points = points + $2,
    "updatedAt" = now()
WHERE id = $1
RETURNING points
`

type AddPointsToUserParams struct {
	ID     string `json:"id"`
	Points int32  `json:"points"`
}

func (q *Queries) AddPointsToUser(ctx context.Context, arg AddPointsToUserParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, addPointsToUser, arg.ID, arg.Points)
	var points int32
	err := row.Scan(&points)
	return points, err
}

const getUserPoints = `-- name: GetUserPoints :one
SELECT points
FROM "user"
WHERE id = $1
`

func (q *Queries) GetUserPoints(ctx context.Context, id string) (int32, error) {
	row := q.db.QueryRowContext(ctx, getUserPoints, id)
	var points int32
	err := row.Scan(&points)
	return points, err
}
